---
abstract: 'execute code, monitor dynamic file contents'
author:
  - 'Joe McMahon, E<lt>mcmahon@yahoo-inc.comE<gt>'
build_requires: {}
configure_requires:
  Module::Build: '0.42'
dynamic_config: 1
generated_by: 'Module::Build version 0.4234, CPAN::Meta::Converter version 2.150010'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Test-Tail-Multi
provides:
  Test::Tail::Multi:
    file: lib/Test/Tail/Multi.pm
    version: '0.07'
requires:
  File::Tail: '0'
  Test::Simple: '0.98'
version: '0.07'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
